# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvvK2dy3pAmQxurqPxaWFqx2gD3JKgCy
"""

# Simple To-Do List Manager in Python

todo_list = []

def show_menu():
    print("\n--- To-Do List Menu ---")
    print("1. View Tasks")
    print("2. Add Task")
    print("3. Mark Task as Completed")
    print("4. Delete Completed Tasks")
    print("5. Exit")

def view_tasks():
    if not todo_list:
        print("Your to-do list is empty.")
    else:
        for i, task in enumerate(todo_list):
            status = "✅" if task['completed'] else "❌"
            print(f"{i + 1}. {task['task']} [{status}]")

def add_task():
    task = input("Enter the task: ")
    todo_list.append({'task': task, 'completed': False})
    print("Task added.")

def mark_completed():
    view_tasks()
    try:
        task_num = int(input("Enter the task number to mark as completed: ")) - 1
        if 0 <= task_num < len(todo_list):
            todo_list[task_num]['completed'] = True
            print("Task marked as completed.")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

def delete_completed():
    global todo_list
    todo_list = [task for task in todo_list if not task['completed']]
    print("Completed tasks removed.")

def main():
    while True:
        show_menu()
        choice = input("Choose an option (1-5): ")
        if choice == '1':
            view_tasks()
        elif choice == '2':
            add_task()
        elif choice == '3':
            mark_completed()
        elif choice == '4':
            delete_completed()
        elif choice == '5':
            print("Goodbye!")
            break
        else:
            print("Invalid option. Please choose again.")

if __name__ == "__main__":
    main()